// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7RE9onWXOGoAPmEsJyc4EnJGTLHoLIw',
    appId: '1:179821695612:web:c83874d4ee96ec9ea1eff9',
    messagingSenderId: '179821695612',
    projectId: 'jeleapps-5561a',
    authDomain: 'jeleapps-5561a.firebaseapp.com',
    storageBucket: 'jeleapps-5561a.firebasestorage.app',
    measurementId: 'G-ZBRB2YDWS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMfWompT091veO4lypY46bX_TAch3qHtY',
    appId: '1:179821695612:android:76432049d5385c01a1eff9',
    messagingSenderId: '179821695612',
    projectId: 'jeleapps-5561a',
    storageBucket: 'jeleapps-5561a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABinUGXSVTtdfQfVVVGfJkkCWLskzqaQw',
    appId: '1:179821695612:ios:50829ce2a5e457d8a1eff9',
    messagingSenderId: '179821695612',
    projectId: 'jeleapps-5561a',
    storageBucket: 'jeleapps-5561a.firebasestorage.app',
    iosBundleId: 'com.example.flutterJeleapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABinUGXSVTtdfQfVVVGfJkkCWLskzqaQw',
    appId: '1:179821695612:ios:50829ce2a5e457d8a1eff9',
    messagingSenderId: '179821695612',
    projectId: 'jeleapps-5561a',
    storageBucket: 'jeleapps-5561a.firebasestorage.app',
    iosBundleId: 'com.example.flutterJeleapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt7RE9onWXOGoAPmEsJyc4EnJGTLHoLIw',
    appId: '1:179821695612:web:fbd6c9ae097b21dea1eff9',
    messagingSenderId: '179821695612',
    projectId: 'jeleapps-5561a',
    authDomain: 'jeleapps-5561a.firebaseapp.com',
    storageBucket: 'jeleapps-5561a.firebasestorage.app',
    measurementId: 'G-58Z2159RJZ',
  );
}
